import 'package:supabase_flutter/supabase_flutter.dart';

import '../../domain/entities/raw_kanjidic.dart';
import '../../domain/repositories/raw_kanjidic_repository.dart';
import '../dto/raw_kanjidic_dto.dart';

class RawKanjidicRepositoryImpl implements RawKanjidicRepository {
  RawKanjidicRepositoryImpl(this._client);

  final SupabaseClient _client;

  static const _table = 'raw_kanjidic';

  @override
  Future<void> insertBatch(List<RawKanjidic> rows) async {
    final payload = rows.map((r) {
      final dto = RawKanjidicDto.fromDomain(r);
      final json = dto.toJson();
      // Remove id — it's auto-generated by the database.
      json.remove('id');
      return json;
    }).toList();
    await _client.from(_table).insert(payload);
  }

  @override
  Future<List<RawKanjidic>> getByImportId(int importId) async {
    final response = await _client
        .from(_table)
        .select()
        .eq('import_id', importId)
        .order('literal');
    return response
        .map((json) => RawKanjidicDto.fromJson(json).toDomain())
        .toList();
  }

  @override
  Future<RawKanjidic?> getByLiteral({
    required int importId,
    required String literal,
  }) async {
    final response = await _client
        .from(_table)
        .select()
        .eq('import_id', importId)
        .eq('literal', literal)
        .maybeSingle();
    if (response == null) return null;
    return RawKanjidicDto.fromJson(response).toDomain();
  }

  @override
  Future<int> countByImportId(int importId) async {
    final response = await _client
        .from(_table)
        .select()
        .eq('import_id', importId)
        .count(CountOption.exact);
    return response.count;
  }
}
