import 'package:supabase_flutter/supabase_flutter.dart';

import '../../domain/entities/raw_kanjivg.dart';
import '../../domain/repositories/raw_kanjivg_repository.dart';
import '../dto/raw_kanjivg_dto.dart';

class RawKanjiVgRepositoryImpl implements RawKanjiVgRepository {
  RawKanjiVgRepositoryImpl(this._client);

  final SupabaseClient _client;

  static const _table = 'raw_kanjivg';

  @override
  Future<void> insertBatch(List<RawKanjiVg> rows) async {
    final payload = rows.map((r) {
      final dto = RawKanjiVgDto.fromDomain(r);
      final json = dto.toJson();
      // Remove id — it's auto-generated by the database.
      json.remove('id');
      return json;
    }).toList();
    await _client.from(_table).insert(payload);
  }

  @override
  Future<List<RawKanjiVg>> getByImportId(int importId) async {
    final response = await _client
        .from(_table)
        .select()
        .eq('import_id', importId)
        .order('character');
    return response
        .map((json) => RawKanjiVgDto.fromJson(json).toDomain())
        .toList();
  }

  @override
  Future<RawKanjiVg?> getByCharacter({
    required int importId,
    required String character,
  }) async {
    final response = await _client
        .from(_table)
        .select()
        .eq('import_id', importId)
        .eq('character', character)
        .maybeSingle();
    if (response == null) return null;
    return RawKanjiVgDto.fromJson(response).toDomain();
  }

  @override
  Future<int> countByImportId(int importId) async {
    final response = await _client
        .from(_table)
        .select()
        .eq('import_id', importId)
        .count(CountOption.exact);
    return response.count;
  }
}
